name = input('type uw naam')
adres = input('type uw adres')
postcode = input('type uw postcode')
woonplaats = input('type uw woonplaats')
print(" ----------------------------------------------------")
print('|  Naam      : ' + name)
print('|  Adres     : ' + adres)
print('|  Postcode  : ' + postcode)
print('|  Woonplaats: ' + woonplaats)
print(' ----------------------------------------------------')
input("Press enter to exit ;)")